batch_size = 1024
num_layers = 12
hidden_dim = 768
edge_embedding_dim = 768
ffn_hidden_dim = 768
n_heads = 32
max_in_degree = 5
max_out_degree = 5
max_path_distance = 5
test_size = 0.8
random_state = 92384
lr = 0.0003
b1 = 0.9
b2 = 0.999
weight_decay = 0.0
eps = 1e-08
clip_grad_norm = 5.0
torch_device = "cuda"
epochs = 1000
lr_power = 0.5
scheduler_type = "polynomial"
lr_patience = 4
lr_cooldown = 2
lr_min = 1e-06
lr_max = 0.001
lr_warmup = 2
lr_smooth = true
lr_window = 10
lr_reset = 0
lr_factor = 0.5
